export enum EPermission {
  CREATE_CATEGORIES = 'create:categories',
  READ_CATEGORIES = 'read:categories',
  UPDATE_CATEGORIES = 'update:categories',
  DELETE_CATEGORIES = 'delete:categories',
  READ_USERS = 'read:users',
  UPDATE_USERS = 'update:users',
  DELETE_USERS = 'delete:users',
  CREATE_THREADS = 'create:threads',
  READ_THREADS = 'read:threads',
  UPDATE_THREADS = 'update:threads',
  DELETE_THREADS = 'delete:threads',
  CREATE_TAGS = 'create:tags',
  READ_TAGS = 'read:tags',
  UPDATE_TAGS = 'update:tags',
  DELETE_TAGS = 'delete:tags',
}
